apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podinfo-data
  namespace: apps
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn