apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  namespace: apps
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: podinfo
  namespaceSelector:
    matchNames:
    - apps
  endpoints:
  - port: http
    interval: 15s